# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3224c2701b3711a1f350964250b13b06ce046ad47f85a494e45f4a564344b1e824914ec35637b0ec61e054aecc35d7336513382f2b6a82e75752d33ee8540584

test:
  secret_key_base: 6829e1db13642a5f1c1797349fa3464d2ad96354e51636376c14ab4134a172066344b80dfaf5b74b11c01db417217d50df2d31157425095d4e2516c120ca2bac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
